### ISSUE TITLE
Add Bookmark option using code from audioanchor

### ISSUE THREAD

**Issue by meximan** [SimpleMobileTools/Simple-Music-Player#344] opened 2021-09-02 08:00 UTC
I definitely prefer the music player than audioanachor for listening to audiobooks and music alike. Its fast and intuitively organized. Plus I like how it automatically adds files and folders quickly from both the internal and SD card storage. Audioanchor tends to freeze and crash when adding files. (Albeit my phone being recently new) also the latest update doesn't allow you to add SD card storage (somehow it was lost)

Please add an ability to create bookmarks. Maybe using the source code from audioanchor. I am sure others would prefer this for the reasons described in the first paragraph. Definitely will make an additional donation if needed to get this feature prioritized.

**Comment by tibbi** [comment] 2021-09-02 15:20
duplicate of #273

**Closed by tibbi** 2021-09-02 15:20 UTC

**Comment by meximan** [comment] 2021-09-02 16:27
Thats for a file list. I am requesting a bookmark to save the time you were at previously. (Example 3 hours into an 8 hour audiobook)

**Comment by meximan** [comment] 2021-09-02 16:27
Its OK I found another app that does this already. Thanks
