### ISSUE TITLE
music player not find some musics

### ISSUE THREAD

**Issue by esmaeelE** [SimpleMobileTools/Simple-Music-Player#436] opened 2022-07-27 01:11 UTC
I accidentally find that music player not show some of my musics.

It seems mp3 files without any metadata like vocalist or picture not recognized. 

When rename the files music player recognize it.

First of all I think space in file name cause this but now it seems only running rename operation on file enough.

For example if the file name is 'asd.mp3' by running rename operation and remove 'd' charach
ter then insert it again to file name cause music player recognize it.

It is weird to me but test it on some files prove this behaviour.

**Comment by tibbi** [comment] 2022-07-27 06:33
how are you renaming the file? With some other app?

**Comment by esmaeelE** [comment] 2022-07-28 20:24
OK, with another cellphone I prove that this behavior.

**Comment by NSTAdventure** [comment] 2022-09-30 15:21
> OK, with another cellphone I prove that this behavior.

Keep in the mind this issues maybe caused by those buggy media player framework apps i have exactly same issues too
Current alternative add music file to playlist manually

**Comment by naveensingh** [comment] 2023-07-19 16:47
@tibbi I think this is a duplicate of the recently closed issues #404 and #394

**Closed** 2023-07-19 17:46 UTC
